### ISSUE TITLE
Provide guidance around the licensing of SF Symbols

### ISSUE THREAD

**Issue by jbmorley** [inseven/symbolic#108]
Since all generated icons make use of SF Symbols, they are covered by that license. I believe there are slightly different licenses for different symbols, but it might be the case that none are considered acceptable for use as app icons, meaning they can only really be used as internal development placeholders.

There's a discussion on the developer forum (https://developer.apple.com/forums/thread/706089) where someone has quoted the following:

> All SF Symbols shall be considered to be system-provided images as defined in the Xcode and Apple SDKs license agreements and are subject to the terms and conditions set forth therein. You may not use SF Symbols — or glyphs that are substantially or confusingly similar — in your app icons, logos, or any other trademark-related use. Apple reserves the right to review and, in its sole discretion, require modification or discontinuance of use of any Symbol used in violation of the foregoing restrictions, and you agree to promptly comply with any such request.

I can't actually seem to find the reference for that guidance right now but it clearly requires further investigation. Should it prove that no SF Symbols can be used in icons, it needs to be made clear in the app that these are for development placeholders only and it seems important to explore other appropriately licensed icon sets (open to suggestions).[^1]

[^1]: I'm pretty sure the Bootstrap icons (https://icons.getbootstrap.com) are MIT licensed, so they might be a good start.

/cc @sfrost007

**Comment by jbmorley** [comment]
Curiously, I still can't seem to find the appropriate clauses. Looking at this Stack Exchange discussion (https://apple.stackexchange.com/questions/437711/sf-symbols-3-0-use-restrictions), it seems that Apple must have removed these explicit clauses from their top-level documentation at least.

**Comment by jbmorley** [comment]
I wonder if perhaps the license has changed with SF Symbols 4 (https://developer.apple.com/sf-symbols/). It's hard to imagine an Apple license becoming more permissive. Some Symbols are very clearly marked in the SF Symbols app as having limited use.

For example, 

<img width="1303" alt="Screenshot 2023-01-11 at 06 01 16" src="https://user-images.githubusercontent.com/220887/211729744-db5102ed-279f-4810-a763-517c926b4d2f.png">

> This symbol may not be modified and may only be used to refer to Apple's iCloud service.

**Comment by jbmorley** [comment]
Related to #111.

**Comment by SFrost007** [comment]
The most current "official" source I've found for this is within the [HIG's section on SFSymbols](https://developer.apple.com/design/human-interface-guidelines/foundations/sf-symbols/):

> _Visit [SF Symbols](https://developer.apple.com/sf-symbols/) to download the app and browse the full set of symbols. **Be sure to understand the terms and conditions for using SF Symbols, including the prohibition against using symbols — or images that are confusingly similar — in app icons, logos, or any other trademarked use.** For developer guidance, see [Configuring and displaying symbol images in your UI](https://developer.apple.com/documentation/uikit/uiimage/configuring_and_displaying_symbol_images_in_your_ui/)._

(emphasis added)

I haven't found the actual "terms and conditions" that refers to though, unless it's within the overall developer agreement (that I haven't checked).

**Comment by jbmorley** [comment]
@SFrost007 Thanks for digging that out. I find it frustrating that I can't actually find a legal document that describes these 'terms and conditions' they keep alluding to, but that does seem pretty unequivocal. Given the generic nature of many of these symbols, I find it fascinating that the phrase "or images that are confusingly similar" is in there, but note that it seems like a weaker version of the initial text [above] that includes, "substantially ... similar".

Given that, I do think the right thing to do is pause here and find some more suitably licensed symbol libraries.

(As an entertaining aside, the Symbolic icon is, naturally, made with Symbolic, and it was approved in App Store review so it's clearly not something they're policing at that point in the system. Of course, that's not really where the problem lies, but it entertained me.)

**Comment by jbmorley** [comment]
Wow. Thank you for digging in–that's incredibly helpful!

It's better to discover at this stage than it is later in the process, so I'm really grateful for you bringing it to my attention. I think that because there's an explicit note next to some of the symbols, I'd assumed the others were fair game. In hindsight, and especially given we're talking about Apple, I should have been more suspicious.

I'm definitely going to rethink things a little prior to a release of the app as I don't want to fall foul of those clauses myself in review, or mislead any users. I'll certainly reference the clause in the app, and maybe even give users a warning on export.

With that in mind, it does also seem important to give users an opportunity to pick other icon sets (perhaps defaulting to something with a more permissive license). Even there though, I worry a little that Apple might decide, for example, that a heart from someone else's symbol library is too close to SF Symbol's heart, and then you're in a world of pain. Still, I don't think providing an app like Symbolic would exacerbate a pre-existing problem of the App Store and Apple's arbitrary rules.

**Comment by jbmorley** [comment]
It looks like while SF Symbols might be great during development, and perhaps even for an internal tool, Apple really doesn't want you using them in icons. Given this, I think the right outcome of this issue would be to ensure users are informed of this, either by a little inline warning in the sidebar when they're using an SF Symbol, or explicitly at export time.
