### ISSUE TITLE
Export over existing export fails

### ISSUE THREAD

**Issue by gingerbeardman** [inseven/symbolic#258]
1. export
2. export again
3. confirm you want to "replace"
4. fails some time later

<img width="272" alt="image" src="https://github.com/user-attachments/assets/33225600-b16d-4d34-98e6-ecaafe465a5b">

**Comment by gingerbeardman** [comment]
Still a problem

<img width="284" alt="Screen shot 2024-10-19 at 15 21 07" src="https://github.com/user-attachments/assets/34f8c549-7957-415a-9a1f-6aff9940c261">

**Comment by jbmorley** [comment]
*nods* I need to submit to the App Store. 😅

**Comment by gingerbeardman** [comment]
oh! HAHAHAHAHA

**Comment by jbmorley** [comment]
Just submitted to the App Store today.
